### ISSUE TITLE
Info on how/where to get google maps API key

### ISSUE THREAD

**Issue by mhulse** [mhulse/kludgy#26]

**Comment by ellieasager** [comment]
This looks like a good source of info: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by mhulse** [comment]
Thanks Ellie! That's great!

I had a friend use this project and he pointed out that the current docs:

https://github.com/mhulse/kludgy/blob/fa39840b0566a9b25b39e9fd8141657ccabb4cd8/README.md

Don't mention anything about how to get the Google Maps API key. Basically, when he ran this code on his machine, he did not realize that the API key used in the above README was a non-functional API key, and that he had to go get his own.

Long story short, I need to add to the README something like:

> **Note:** The API in this example _does not work_. **It is required that you use a valid/working Google Maps API key.** In order to obtain a key, visit: [Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/get-api-key)

Or, something like that.  Do you have any feedback on how it should be worded in order for new users to understand how to get this code working?

With that said, thanks for the linkage! Now I just need to edit the README! Hehe. 😆

**Comment by mhulse** [comment]
Added to wiki: https://github.com/mhulse/kludgy/wiki/Google-Maps-API-key

Closing.
