### ISSUE TITLE
Feature request: assign to single display

### ISSUE THREAD

**Issue by beekman** [mhulse/kludgy#27]
Feature request: ability to assign a kludgy to a specific display when multiple displays are connected. Don't know if this is tough but it would be cool if not.

**Comment by mhulse** [comment]
Oh, I think it's totally possible.

The latest version of OSX uses an sqlite db. I have been meaning to learn more about it (my work computer doesn't set the first desktop when running Kludgy, only the second. See #25)

Anyway, great feature idea. I don't think it'd be hard once I crack the desktop background schema.

**Comment by mhulse** [comment]
In the upcoming v2 codebase, the new rule will be to use the OS X system pref to manage desktop background images.

Closing in favor of that technique. It's gonna be awesome!

Thanks for the issue, ideas and help!
